### ISSUE TITLE
Random Slow Signing Requests

### ISSUE THREAD

**Issue by bobot4258** [Azure/trusted-signing-action#39]
We recently implemented Azure Trusted Signing with signtool using the WUS2 region.  We are getting random slow signing requests that take 3 minutes whereas others take 3 seconds.  I see under the server selection area on the Github page it makes mention of a very similar issue occurring in the WUS region.  

Could this same issue also be occurring in the WUS2 region as well? 

![image](https://github.com/Azure/trusted-signing-action/assets/49081331/0436ce20-b8ec-4a13-9b8b-12a358bc9d9e)

**Comment by japarson** [comment]
@bobot4258 Are you still experiencing this issue? I believe there was a temporary issue that has been resolved.

**Comment by bobot4258** [comment]
Hi @japarson,

Thanks for following up, the issue seems to be fixed as we are not experiencing it anymore,
