### ISSUE TITLE
Rename code-signing-account-name option?

### ISSUE THREAD

**Issue by dlemstra** [Azure/trusted-signing-action#4]
It might be a good idea to rename `code-signing-account-name` to `trusted-signing-account-name`? And it also looks like the readme could use an update in the option descriptions.

**Comment by sudara** [comment]
In case it helps: On the public preview announcement, the team reported the reasoning for keeping the deprecated naming was to avoid breaking compatibility for the people who were on the private preview.

Perhaps some logic could be added so that both the old/new naming schemes would work?

**Comment by dlemstra** [comment]
Sounds like a good idea to allow both names and raise a warning when the old name is used?

**Comment by japarson** [comment]
Thank you for pointing this out. I tried so hard to rename everything and just completely overlooked this.

> Sounds like a good idea to allow both names and raise a warning when the old name is used?
I like this idea. Would you like to open a PR? If not, I'll get to it when I have time.

**Comment by dlemstra** [comment]
I have created this PR: #14. When will you publish the powershell module on GitHub so we (me) can do the same there?

**Comment by japarson** [comment]
Closed by https://github.com/Azure/trusted-signing-action/pull/14
