### ISSUE TITLE
Azure/azure-code-signing-action deprecated?

### ISSUE THREAD

**Issue by devm33** [Azure/trusted-signing-action#45]
It looks like the https://github.com/Azure/azure-code-signing-action repo (and therefore the action) was removed. Breaking workflows using the action.

Was this an intentional deprecation? Apologies if I missed any deprecation notices on this.

Also, is this repo/action `Azure/trusted-signing-action` meant to be a drop-in replacement for `Azure/azure-code-signing-action`? Appears to be the case, but want to be sure.

**Comment by japarson** [comment]
Hi @devm33, I apologize for the disruption to your workflows. The deprecation and removal were intentional. You should be able to use the Trusted Signing action as a drop-in replacement with no changes to your input parameters. Let me know if you run into any issues.

**Comment by devm33** [comment]
@japarson thanks for confirming!

**Comment by samsiddiquiz** [comment]
@devm33 
Where can I find the signed file after the successful completion of the workflow? I am unable to see any changes.

**Comment by japarson** [comment]
> @devm33 Where can I find the signed file after the successful completion of the workflow? I am unable to see any changes.

Hi @samsiddiquiz, the files are signed in place. They do not get copied to any output directory. To check if a file is signed, you can download it to a Windows machine -> right-click -> properties -> Digital Signatures -> verify your the expected signature is present.
