### ISSUE TITLE
When will the changes for Click Once be available

### ISSUE THREAD

**Issue by GeetarmanAgilico** [Azure/trusted-signing-action#56]
The changes for Clickonce signing are not yet available because the latest version is still v0.4.0 and these changes require v0.5.0.
When will these changes be available?

**Comment by GeetarmanAgilico** [comment]
I copied and ran this instead from my own repository on my own self-hosted runner in the meantime.  I had to fiddle around with the location of the sign cli tool but otherwise I got it to succesfully sign a .vsto file.

**Comment by japarson** [comment]
@GeetarmanAgilico Available now. What changes did you have to implement to get it working?

**Comment by GeetarmanAgilico** [comment]
OK thanks.  It was just a pathing issue to the sign cli tool thats all...  I just ended up copying it to the location it was looking for it in.
