### ISSUE TITLE
Use a default value for timestamp-digest?

### ISSUE THREAD

**Issue by dlemstra** [Azure/trusted-signing-action#6]
I was wondering if a default value could be set for the `timestamp-digest` of the RFC3161 compliant timestamping service? This would require changes in the powershell script:

```powershell
if ($TimestampRfc3161) {
    $result.Add("/tr")
    $result.Add($TimestampRfc3161)
    $result.Add("/td")
    if ($TimestampDigest) {
        $result.Add($TimestampDigest)
    } else {
        $result.Add("SHA256")
    }
}
```

But that can probably also be done in the action instead. If the latter is preferred I can open a pull request for this.

**Comment by sudara** [comment]
This would be great to reduce the amount of boilerplate needed for the action!

**Comment by japarson** [comment]
Hi @dlemstra @sudara,

There are default values for the timestamping options here:
https://github.com/Azure/trusted-signing-action/blob/b0b40558520b25479414d349890d63bdaa8e399f/action.yml#L66-L73

Please let me know if this is what you're looking for or not.

**Comment by dlemstra** [comment]
That default value for `SHA256` was added 26 minutes ago? 😉

**Comment by sudara** [comment]
This is great for me, I just wanted more concise config. I can also see why it would make sense to have the default in powershell..

**Comment by japarson** [comment]
> ~That default value for `SHA256` was added 26 minutes ago? 😉~ Just saw that is was a PR to change this.
> 
> Wondering if I misread your comment but this is what I was expecting to be added. But I do wonder if this should be done in the powershell script instead?

@dlemstra I commented on my philosophy around defaults/required in action/powershell [here](https://github.com/Azure/trusted-signing-action/issues/7#issuecomment-2099155186). We can continue the conversation there.
