### ISSUE TITLE
Add `file` option to just sign one single known filename

### ISSUE THREAD

**Issue by sudara** [Azure/trusted-signing-action#9]
The example has a somewhat advanced usage of `files-folder` and `files-folder-filter` which makes the assumption people are signing multiple files (but not all) within a directory.

It would be great if there was a `file` option for doing the simple thing of signing a single file. 

Thanks!!

**Comment by japarson** [comment]
We can add a new parameter `files:` that is a comma separated list of relative or absolute file paths. This would also support the scenario of just 1 file.

@sudara What do you think?

**Comment by sudara** [comment]
Sure! That would be sweet...

**Comment by rwsdwatson** [comment]
This would be great.

**Comment by riverar** [comment]
I'd like this too. The current method ends up signing a bunch of ancillary .NET files for self-contained applications.

**Comment by japarson** [comment]
Added in v0.4.0
